### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by romanskorobagatko** [liu-qilong/obsidian-setup#1]
Hello! I'm new to Obsidian and really like the approach of your setup, but struggling to figure out how to set this up.
Cloud you please add a description or make a short YouTube video tutorial?

**Comment by liu-qilong** [comment]
> Hello! I'm new to Obsidian and really like the approach of your setup, but struggling to figure out how to set this up. Cloud you please add a description or make a short YouTube video tutorial?

May I ask which part you are most interested in trying? The `PaperThread`, the `TagLens`, or the `DailyLens` part? I might need some more time to write a complete setup guide cuz I'm a little bit busy now... But I can write a brief guide on a specific part for you.

**Comment by romanskorobagatko** [comment]
TagLens and DailyLens would be amazing, thanks in advance!

**Comment by liu-qilong** [comment]
> TagLens and DailyLens would be amazing, thanks in advance!

Hi, I have written a complete setup guide. Please refer to the README. A ready-to-use vault can be downloaded from the Releases.
